apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moestream-uploads
  namespace: moestream
  labels:
    app.kubernetes.io/name: moestream
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moestream-data
  namespace: moestream
  labels:
    app.kubernetes.io/name: moestream
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moestream-postgres
  namespace: moestream
  labels:
    app.kubernetes.io/name: moestream
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moestream-redis
  namespace: moestream
  labels:
    app.kubernetes.io/name: moestream
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
